/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlogCardList: typeof import('./src/components/BlogCardList.vue')['default']
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MessageDefalutGrid: typeof import('./src/components/MessageDefalutGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamCardList: typeof import('./src/components/TeamCardList.vue')['default']
    TeamMemberCardList: typeof import('./src/components/TeamMemberCardList.vue')['default']
    UserCardList: typeof import('./src/components/UserCardList.vue')['default']
    UserCommentList: typeof import('./src/components/UserCommentList.vue')['default']
    UserLikeList: typeof import('./src/components/UserLikeList.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
